### PR TITLE
v2.1.3

### PR DESCRIPTION
**Pull request by michael-okeefe**
# FASTSim release 2.1.3

## Remaining Tasks

- [x] push new version of crates to crates.io
- [x] investigate using a token to automate pushing crates to crates.io (see below)
- [x] ensure tests complete

## Publishing Crates via Github Actions

Resources for publishing crates via Github Actions:

- https://pratikpc.medium.com/publishing-crates-using-github-actions-165ee67780e1
- https://github.com/marketplace/actions/publish-crates
- https://github.com/wraithan/cargo-bump

### CODE REVIEW

**Comment by michael-okeefe** [comment]
FYI, resources for publishing crates via Github Actions:

- https://pratikpc.medium.com/publishing-crates-using-github-actions-165ee67780e1
- https://github.com/marketplace/actions/publish-crates
- https://github.com/wraithan/cargo-bump

**Comment by kylecarow** [comment]
@michael-okeefe can you move the tag to the latest commit to start up the wheels tests again?

**Comment by michael-okeefe** [comment]
> @michael-okeefe can you move the tag to the latest commit to start up the wheels tests again?

Will do.

**Comment by michael-okeefe** [comment]
@kylecarow Should be running the wheels builds now.

**Comment by kylecarow** [comment]
The 403 error is pretty confusing to me. I get 403 errors sporadically on my machine, so I'm not sure if this is just an API issue.

There definitely was an error that I fixed with the fastsim-2 merge above, though.

**Comment by michael-okeefe** [comment]
> The 403 error is pretty confusing to me. I get 403 errors sporadically on my machine, so I'm not sure if this is just an API issue.
> 
> There definitely was an error that I fixed with the fastsim-2 merge above, though.

OK, that's good to know. The URL in question is this one, I think (according to the error message at least): https://api.github.com/repos/NREL/fastsim-vehicles/contents

I can hit it consistently from the browser and a trace shows there are no re-directs so it is very puzzling to get a 403...

https://wheregoes.com/trace/20245307711/

I just manually triggered a py3.10 windows build and it passed OK. Curiouser and curiouser...

**Comment by michael-okeefe** [comment]
@kylecarow I wonder if this is the problem:
https://stackoverflow.com/a/70179239

**Comment by calbaker** [comment]
@michael-okeefe @kylecarow 
Where are we at with this one?

**Comment by michael-okeefe** [comment]
@calbaker (@kylecarow ) This PR doesn't incorporate the "disable network based tests" functionality which was causing some test failures (403 http status code) initially. I added functionality to fix that on another PR that got merged. For the tests here, I manually triggered them to re-run as necessary to pass the network based unit tests (that were periodically failing).

The branch itself should be valid and ready to merge.

**Review by calbaker — APPROVED** [review]

**Comment by calbaker** [comment]
@michael-okeefe , since I merged this, could you please go ahead and release 2.1.3 to PyPI?  Is that now automated?

**Comment by michael-okeefe** [comment]
@calbaker there might be a slicker way to do this, but I manually triggered the release branch here:

https://github.com/NREL/fastsim/actions/runs/12244359445

If/when it completes the tests, it should deploy to PyPI.

**Comment by michael-okeefe** [comment]
@calbaker Looks like there are some problems with `release.yaml` -- I think I know what the issue is but I'm going to pull that into another PR / branch to fix. Will keep you updated.

**Pull request merged**
