### PR TITLE
made diff generic and used it for dist

### PR DESCRIPTION
**Pull request by kylecarow**
Not sure that I implemented this in the best way, so check that out. It does a copy (via deref) on both values, there may be a better way.

### CODE REVIEW

**Comment by calbaker** [comment]
@kylecarow , nicely done!  

@robinsteuteville, check out the cool trait stuff Kyle did in this PR.

**Comment by nreinicke** [comment]
@kylecarow - Sorry I'm late looking at this but I'm wondering if you could implement the Diff trait by operating on cloned references instead of copying the underlying type?

```rust
pub trait Diff<T> {
    fn diff(&self) -> Vec<T>;
}

impl<T: Sub<Output = T> + Clone> Diff<T> for Vec<T> {
    fn diff(&self) -> Vec<T> {
        self.windows(2)
            .map(|vs| {
                let x = &vs[0];
                let y = &vs[1];
                y.clone() - x.clone()
            })
            .collect()
    }
}
```

Cloning the reference vs copying a float are probably similar performance wise but it might make a big difference if `T` is a bigger heap allocated type.

**Comment by calbaker** [comment]
@nreinicke , when we have
```rust
    fn diff(&self) -> Vec<T> {
        let mut v_diff: Vec<T> = vec![Default::default()];
        v_diff.extend::<Vec<T>>(
            self.windows(2)
                .map(|vs| {
                    let x = &vs[0];
                    let y = &vs[1];
                    y.clone() - x.clone()
                })
                .collect(),
        );
        v_diff
    }

```

we get 
```
warning: using `clone` on type `T` which implements the `Copy` trait
   --> fastsim-core/src/traits.rs:393:21
    |
393 |                     y.clone() - x.clone()
    |                     ^^^^^^^^^ help: try dereferencing it: `*y`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy
    = note: `#[warn(clippy::clone_on_copy)]` on by default

warning: using `clone` on type `T` which implements the `Copy` trait
   --> fastsim-core/src/traits.rs:393:33
    |
393 |                     y.clone() - x.clone()
    |                                 ^^^^^^^^^ help: try dereferencing it: `*x`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy
```

**Comment by nreinicke** [comment]
I guess this makes a good point in that if you're implementing this trait on a datatype that implements `Copy`, like `f64`, you're probably better off just doing it the original way (de-referencing) but if you're implementing this on a datatype that is heap allocated and expensive to clone, cloning by reference would be better.

**Pull request merged**
